jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '25.0.0'

      - name: Install dependencies
        run: npm install

      - name: Build Docusaurus site
        run: npm run build

      - name: Configure Git user
        run: |
          git config --global user.name "sparshjaswal"
          git config --global user.email "jaswalsparsh@gmail.com"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_USER: sparshjaswal
        run: npm run deploy
